// @generated by torchgen/gen.py from ViewMetaClasses.cpp

#include <ATen/FunctionalInverses.h>
#include <ATen/ViewMetaClasses.h>

#ifndef AT_PER_OPERATOR_HEADERS
#include <ATen/Operators.h>
#include <ATen/NativeFunctions.h>
#else
#include <ATen/ops/_fw_primal_native.h>
#include <ATen/ops/_fw_primal_ops.h>
#include <ATen/ops/_fw_primal_copy_native.h>
#include <ATen/ops/_fw_primal_copy_ops.h>
#include <ATen/ops/_make_dual_native.h>
#include <ATen/ops/_make_dual_ops.h>
#include <ATen/ops/_make_dual_copy_native.h>
#include <ATen/ops/_make_dual_copy_ops.h>
#include <ATen/ops/_unpack_dual_native.h>
#include <ATen/ops/_unpack_dual_ops.h>
#include <ATen/ops/rename_native.h>
#include <ATen/ops/rename_ops.h>
#include <ATen/ops/align_to_native.h>
#include <ATen/ops/align_to_ops.h>
#include <ATen/ops/align_to_native.h>
#include <ATen/ops/align_to_ops.h>
#include <ATen/ops/refine_names_native.h>
#include <ATen/ops/refine_names_ops.h>
#include <ATen/ops/view_as_real_native.h>
#include <ATen/ops/view_as_real_ops.h>
#include <ATen/ops/view_as_real_copy_native.h>
#include <ATen/ops/view_as_real_copy_ops.h>
#include <ATen/ops/view_as_complex_native.h>
#include <ATen/ops/view_as_complex_ops.h>
#include <ATen/ops/view_as_complex_copy_native.h>
#include <ATen/ops/view_as_complex_copy_ops.h>
#include <ATen/ops/real_native.h>
#include <ATen/ops/real_ops.h>
#include <ATen/ops/imag_native.h>
#include <ATen/ops/imag_ops.h>
#include <ATen/ops/_conj_native.h>
#include <ATen/ops/_conj_ops.h>
#include <ATen/ops/_conj_copy_native.h>
#include <ATen/ops/_conj_copy_ops.h>
#include <ATen/ops/conj_native.h>
#include <ATen/ops/conj_ops.h>
#include <ATen/ops/resolve_conj_native.h>
#include <ATen/ops/resolve_conj_ops.h>
#include <ATen/ops/resolve_neg_native.h>
#include <ATen/ops/resolve_neg_ops.h>
#include <ATen/ops/_neg_view_native.h>
#include <ATen/ops/_neg_view_ops.h>
#include <ATen/ops/_neg_view_copy_native.h>
#include <ATen/ops/_neg_view_copy_ops.h>
#include <ATen/ops/as_strided_native.h>
#include <ATen/ops/as_strided_ops.h>
#include <ATen/ops/as_strided_copy_native.h>
#include <ATen/ops/as_strided_copy_ops.h>
#include <ATen/ops/broadcast_to_native.h>
#include <ATen/ops/broadcast_to_ops.h>
#include <ATen/ops/_sparse_broadcast_to_native.h>
#include <ATen/ops/_sparse_broadcast_to_ops.h>
#include <ATen/ops/_sparse_broadcast_to_copy_native.h>
#include <ATen/ops/_sparse_broadcast_to_copy_ops.h>
#include <ATen/ops/chunk_native.h>
#include <ATen/ops/chunk_ops.h>
#include <ATen/ops/tensor_split_native.h>
#include <ATen/ops/tensor_split_ops.h>
#include <ATen/ops/tensor_split_native.h>
#include <ATen/ops/tensor_split_ops.h>
#include <ATen/ops/tensor_split_native.h>
#include <ATen/ops/tensor_split_ops.h>
#include <ATen/ops/contiguous_native.h>
#include <ATen/ops/contiguous_ops.h>
#include <ATen/ops/diagonal_native.h>
#include <ATen/ops/diagonal_ops.h>
#include <ATen/ops/diagonal_copy_native.h>
#include <ATen/ops/diagonal_copy_ops.h>
#include <ATen/ops/linalg_diagonal_native.h>
#include <ATen/ops/linalg_diagonal_ops.h>
#include <ATen/ops/diagonal_native.h>
#include <ATen/ops/diagonal_ops.h>
#include <ATen/ops/expand_native.h>
#include <ATen/ops/expand_ops.h>
#include <ATen/ops/expand_copy_native.h>
#include <ATen/ops/expand_copy_ops.h>
#include <ATen/ops/expand_as_native.h>
#include <ATen/ops/expand_as_ops.h>
#include <ATen/ops/flatten_native.h>
#include <ATen/ops/flatten_ops.h>
#include <ATen/ops/flatten_native.h>
#include <ATen/ops/flatten_ops.h>
#include <ATen/ops/flatten_native.h>
#include <ATen/ops/flatten_ops.h>
#include <ATen/ops/flatten_native.h>
#include <ATen/ops/flatten_ops.h>
#include <ATen/ops/unflatten_native.h>
#include <ATen/ops/unflatten_ops.h>
#include <ATen/ops/unflatten_native.h>
#include <ATen/ops/unflatten_ops.h>
#include <ATen/ops/narrow_native.h>
#include <ATen/ops/narrow_ops.h>
#include <ATen/ops/narrow_copy_native.h>
#include <ATen/ops/narrow_copy_ops.h>
#include <ATen/ops/narrow_native.h>
#include <ATen/ops/narrow_ops.h>
#include <ATen/ops/permute_native.h>
#include <ATen/ops/permute_ops.h>
#include <ATen/ops/permute_copy_native.h>
#include <ATen/ops/permute_copy_ops.h>
#include <ATen/ops/movedim_native.h>
#include <ATen/ops/movedim_ops.h>
#include <ATen/ops/movedim_native.h>
#include <ATen/ops/movedim_ops.h>
#include <ATen/ops/moveaxis_native.h>
#include <ATen/ops/moveaxis_ops.h>
#include <ATen/ops/moveaxis_native.h>
#include <ATen/ops/moveaxis_ops.h>
#include <ATen/ops/numpy_T_native.h>
#include <ATen/ops/numpy_T_ops.h>
#include <ATen/ops/matrix_H_native.h>
#include <ATen/ops/matrix_H_ops.h>
#include <ATen/ops/mT_native.h>
#include <ATen/ops/mT_ops.h>
#include <ATen/ops/mH_native.h>
#include <ATen/ops/mH_ops.h>
#include <ATen/ops/adjoint_native.h>
#include <ATen/ops/adjoint_ops.h>
#include <ATen/ops/pin_memory_native.h>
#include <ATen/ops/pin_memory_ops.h>
#include <ATen/ops/ravel_native.h>
#include <ATen/ops/ravel_ops.h>
#include <ATen/ops/reshape_native.h>
#include <ATen/ops/reshape_ops.h>
#include <ATen/ops/_reshape_alias_native.h>
#include <ATen/ops/_reshape_alias_ops.h>
#include <ATen/ops/_reshape_alias_copy_native.h>
#include <ATen/ops/_reshape_alias_copy_ops.h>
#include <ATen/ops/reshape_as_native.h>
#include <ATen/ops/reshape_as_ops.h>
#include <ATen/ops/select_native.h>
#include <ATen/ops/select_ops.h>
#include <ATen/ops/select_native.h>
#include <ATen/ops/select_ops.h>
#include <ATen/ops/select_copy_native.h>
#include <ATen/ops/select_copy_ops.h>
#include <ATen/ops/detach_native.h>
#include <ATen/ops/detach_ops.h>
#include <ATen/ops/detach_copy_native.h>
#include <ATen/ops/detach_copy_ops.h>
#include <ATen/ops/slice_native.h>
#include <ATen/ops/slice_ops.h>
#include <ATen/ops/slice_copy_native.h>
#include <ATen/ops/slice_copy_ops.h>
#include <ATen/ops/slice_inverse_native.h>
#include <ATen/ops/slice_inverse_ops.h>
#include <ATen/ops/slice_scatter_native.h>
#include <ATen/ops/slice_scatter_ops.h>
#include <ATen/ops/split_native.h>
#include <ATen/ops/split_ops.h>
#include <ATen/ops/split_copy_native.h>
#include <ATen/ops/split_copy_ops.h>
#include <ATen/ops/split_native.h>
#include <ATen/ops/split_ops.h>
#include <ATen/ops/split_with_sizes_native.h>
#include <ATen/ops/split_with_sizes_ops.h>
#include <ATen/ops/split_with_sizes_copy_native.h>
#include <ATen/ops/split_with_sizes_copy_ops.h>
#include <ATen/ops/hsplit_native.h>
#include <ATen/ops/hsplit_ops.h>
#include <ATen/ops/hsplit_native.h>
#include <ATen/ops/hsplit_ops.h>
#include <ATen/ops/vsplit_native.h>
#include <ATen/ops/vsplit_ops.h>
#include <ATen/ops/vsplit_native.h>
#include <ATen/ops/vsplit_ops.h>
#include <ATen/ops/dsplit_native.h>
#include <ATen/ops/dsplit_ops.h>
#include <ATen/ops/dsplit_native.h>
#include <ATen/ops/dsplit_ops.h>
#include <ATen/ops/squeeze_native.h>
#include <ATen/ops/squeeze_ops.h>
#include <ATen/ops/squeeze_copy_native.h>
#include <ATen/ops/squeeze_copy_ops.h>
#include <ATen/ops/squeeze_native.h>
#include <ATen/ops/squeeze_ops.h>
#include <ATen/ops/squeeze_copy_native.h>
#include <ATen/ops/squeeze_copy_ops.h>
#include <ATen/ops/squeeze_native.h>
#include <ATen/ops/squeeze_ops.h>
#include <ATen/ops/squeeze_native.h>
#include <ATen/ops/squeeze_ops.h>
#include <ATen/ops/squeeze_copy_native.h>
#include <ATen/ops/squeeze_copy_ops.h>
#include <ATen/ops/t_native.h>
#include <ATen/ops/t_ops.h>
#include <ATen/ops/t_copy_native.h>
#include <ATen/ops/t_copy_ops.h>
#include <ATen/ops/transpose_native.h>
#include <ATen/ops/transpose_ops.h>
#include <ATen/ops/transpose_copy_native.h>
#include <ATen/ops/transpose_copy_ops.h>
#include <ATen/ops/transpose_native.h>
#include <ATen/ops/transpose_ops.h>
#include <ATen/ops/_nested_view_from_buffer_native.h>
#include <ATen/ops/_nested_view_from_buffer_ops.h>
#include <ATen/ops/_nested_view_from_buffer_copy_native.h>
#include <ATen/ops/_nested_view_from_buffer_copy_ops.h>
#include <ATen/ops/_nested_view_from_jagged_native.h>
#include <ATen/ops/_nested_view_from_jagged_ops.h>
#include <ATen/ops/_nested_view_from_jagged_copy_native.h>
#include <ATen/ops/_nested_view_from_jagged_copy_ops.h>
#include <ATen/ops/_nested_get_values_native.h>
#include <ATen/ops/_nested_get_values_ops.h>
#include <ATen/ops/_nested_get_values_copy_native.h>
#include <ATen/ops/_nested_get_values_copy_ops.h>
#include <ATen/ops/unsqueeze_native.h>
#include <ATen/ops/unsqueeze_ops.h>
#include <ATen/ops/unsqueeze_copy_native.h>
#include <ATen/ops/unsqueeze_copy_ops.h>
#include <ATen/ops/view_as_native.h>
#include <ATen/ops/view_as_ops.h>
#include <ATen/ops/positive_native.h>
#include <ATen/ops/positive_ops.h>
#include <ATen/ops/coalesce_native.h>
#include <ATen/ops/coalesce_ops.h>
#include <ATen/ops/_indices_native.h>
#include <ATen/ops/_indices_ops.h>
#include <ATen/ops/_indices_copy_native.h>
#include <ATen/ops/_indices_copy_ops.h>
#include <ATen/ops/_values_native.h>
#include <ATen/ops/_values_ops.h>
#include <ATen/ops/_values_copy_native.h>
#include <ATen/ops/_values_copy_ops.h>
#include <ATen/ops/indices_native.h>
#include <ATen/ops/indices_ops.h>
#include <ATen/ops/indices_copy_native.h>
#include <ATen/ops/indices_copy_ops.h>
#include <ATen/ops/values_native.h>
#include <ATen/ops/values_ops.h>
#include <ATen/ops/values_copy_native.h>
#include <ATen/ops/values_copy_ops.h>
#include <ATen/ops/crow_indices_native.h>
#include <ATen/ops/crow_indices_ops.h>
#include <ATen/ops/crow_indices_copy_native.h>
#include <ATen/ops/crow_indices_copy_ops.h>
#include <ATen/ops/col_indices_native.h>
#include <ATen/ops/col_indices_ops.h>
#include <ATen/ops/col_indices_copy_native.h>
#include <ATen/ops/col_indices_copy_ops.h>
#include <ATen/ops/ccol_indices_native.h>
#include <ATen/ops/ccol_indices_ops.h>
#include <ATen/ops/ccol_indices_copy_native.h>
#include <ATen/ops/ccol_indices_copy_ops.h>
#include <ATen/ops/row_indices_native.h>
#include <ATen/ops/row_indices_ops.h>
#include <ATen/ops/row_indices_copy_native.h>
#include <ATen/ops/row_indices_copy_ops.h>
#include <ATen/ops/unbind_native.h>
#include <ATen/ops/unbind_ops.h>
#include <ATen/ops/unbind_copy_native.h>
#include <ATen/ops/unbind_copy_ops.h>
#include <ATen/ops/unbind_native.h>
#include <ATen/ops/unbind_ops.h>
#include <ATen/ops/_autocast_to_reduced_precision_native.h>
#include <ATen/ops/_autocast_to_reduced_precision_ops.h>
#include <ATen/ops/_autocast_to_full_precision_native.h>
#include <ATen/ops/_autocast_to_full_precision_ops.h>
#include <ATen/ops/to_native.h>
#include <ATen/ops/to_ops.h>
#include <ATen/ops/to_native.h>
#include <ATen/ops/to_ops.h>
#include <ATen/ops/to_native.h>
#include <ATen/ops/to_ops.h>
#include <ATen/ops/to_native.h>
#include <ATen/ops/to_ops.h>
#include <ATen/ops/lift_fresh_native.h>
#include <ATen/ops/lift_fresh_ops.h>
#include <ATen/ops/lift_fresh_copy_native.h>
#include <ATen/ops/lift_fresh_copy_ops.h>
#include <ATen/ops/view_native.h>
#include <ATen/ops/view_ops.h>
#include <ATen/ops/view_copy_native.h>
#include <ATen/ops/view_copy_ops.h>
#include <ATen/ops/view_native.h>
#include <ATen/ops/view_ops.h>
#include <ATen/ops/view_copy_native.h>
#include <ATen/ops/view_copy_ops.h>
#include <ATen/ops/swapaxes_native.h>
#include <ATen/ops/swapaxes_ops.h>
#include <ATen/ops/swapdims_native.h>
#include <ATen/ops/swapdims_ops.h>
#include <ATen/ops/unfold_native.h>
#include <ATen/ops/unfold_ops.h>
#include <ATen/ops/unfold_copy_native.h>
#include <ATen/ops/unfold_copy_ops.h>
#include <ATen/ops/alias_native.h>
#include <ATen/ops/alias_ops.h>
#include <ATen/ops/alias_copy_native.h>
#include <ATen/ops/alias_copy_ops.h>
#include <ATen/ops/_test_autograd_multiple_dispatch_view_native.h>
#include <ATen/ops/_test_autograd_multiple_dispatch_view_ops.h>
#include <ATen/ops/_test_autograd_multiple_dispatch_view_copy_native.h>
#include <ATen/ops/_test_autograd_multiple_dispatch_view_copy_ops.h>
#endif

namespace at {
namespace functionalization {


at::Tensor _fw_primal_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_fw_primal::call(base, level);
  } else {
    return at::_ops::_fw_primal_copy::call(base, level);
  }
}

at::Tensor _fw_primal_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_fw_primal_inverse(base, mutated_view, inverse_return_mode, level);
}

at::Tensor _make_dual_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_make_dual::call(base, tangent, level);
  } else {
    return at::_ops::_make_dual_copy::call(base, tangent, level);
  }
}

at::Tensor _make_dual_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_make_dual_inverse(base, mutated_view, inverse_return_mode, tangent, level);
}

at::Tensor view_as_real_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::view_as_real::call(base);
  } else {
    return at::_ops::view_as_real_copy::call(base);
  }
}

at::Tensor view_as_real_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::view_as_real_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor view_as_complex_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::view_as_complex::call(base);
  } else {
    return at::_ops::view_as_complex_copy::call(base);
  }
}

at::Tensor view_as_complex_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::view_as_complex_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor _conj_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_conj::call(base);
  } else {
    return at::_ops::_conj_copy::call(base);
  }
}

at::Tensor _conj_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_conj_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor _neg_view_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_neg_view::call(base);
  } else {
    return at::_ops::_neg_view_copy::call(base);
  }
}

at::Tensor _neg_view_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_neg_view_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor as_strided_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::as_strided::call(base, size, stride, storage_offset);
  } else {
    return at::_ops::as_strided_copy::call(base, size, stride, storage_offset);
  }
}

at::Tensor as_strided_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::as_strided_inverse(base, mutated_view, inverse_return_mode, size, stride, storage_offset);
}

at::Tensor as_strided__ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::as_strided::call(base, size, stride, storage_offset);
  } else {
    return at::_ops::as_strided_copy::call(base, size, stride, storage_offset);
  }
}

at::Tensor as_strided__ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::as_strided_inverse(base, mutated_view, inverse_return_mode, size, stride, storage_offset);
}

at::Tensor _sparse_broadcast_to_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_sparse_broadcast_to::call(base, size);
  } else {
    return at::_ops::_sparse_broadcast_to_copy::call(base, size);
  }
}

at::Tensor _sparse_broadcast_to_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_sparse_broadcast_to_inverse(base, mutated_view, inverse_return_mode, size);
}

at::Tensor diagonal_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::diagonal::call(base, offset, dim1, dim2);
  } else {
    return at::_ops::diagonal_copy::call(base, offset, dim1, dim2);
  }
}

at::Tensor diagonal_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::diagonal_inverse(base, mutated_view, inverse_return_mode, offset, dim1, dim2);
}

at::Tensor expand_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::expand::call(base, size, implicit);
  } else {
    return at::_ops::expand_copy::call(base, size, implicit);
  }
}

at::Tensor expand_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::expand_inverse(base, mutated_view, inverse_return_mode, size, implicit);
}

at::Tensor permute_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::permute::call(base, dims);
  } else {
    return at::_ops::permute_copy::call(base, dims);
  }
}

at::Tensor permute_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::permute_inverse(base, mutated_view, inverse_return_mode, dims);
}

at::Tensor _reshape_alias_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_reshape_alias::call(base, size, stride);
  } else {
    return at::_ops::_reshape_alias_copy::call(base, size, stride);
  }
}

at::Tensor _reshape_alias_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_reshape_alias_inverse(base, mutated_view, inverse_return_mode, size, stride);
}

at::Tensor select_int_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::select_int::call(base, dim, index);
  } else {
    return at::_ops::select_copy_int::call(base, dim, index);
  }
}

at::Tensor select_int_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::select_int_inverse(base, mutated_view, inverse_return_mode, dim, index);
}

at::Tensor detach_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::detach::call(base);
  } else {
    return at::_ops::detach_copy::call(base);
  }
}

at::Tensor detach_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::detach_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor detach__ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::detach::call(base);
  } else {
    return at::_ops::detach_copy::call(base);
  }
}

at::Tensor detach__ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::detach_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor slice_Tensor_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::slice_Tensor::call(base, dim, start, end, step);
  } else {
    return at::_ops::slice_copy_Tensor::call(base, dim, start, end, step);
  }
}

at::Tensor slice_Tensor_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::slice_Tensor_inverse(base, mutated_view, inverse_return_mode, dim, start, end, step);
}

at::Tensor slice_inverse_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::slice_inverse::call(base, src, dim, start, end, step);
  } else {
    return at::_ops::slice_scatter::call(base, src, dim, start, end, step);
  }
}

at::Tensor slice_inverse_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::slice_inverse_inverse(base, mutated_view, inverse_return_mode, src, dim, start, end, step);
}

at::Tensor split_Tensor_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::split_Tensor::call(base, split_size, dim)[out_index];
  } else {
    return at::_ops::split_copy_Tensor::call(base, split_size, dim)[out_index];
  }
}

at::Tensor split_Tensor_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::split_Tensor_inverse(base, mutated_view, inverse_return_mode, out_index, split_size, dim);
}

std::shared_ptr<at::functionalization::ViewMeta> split_Tensor_ViewMeta::to_out_index(int64_t out_index) {
  return std::make_shared<at::functionalization::split_Tensor_ViewMeta>(has_symbolic_inputs, out_index, reapply_views, inverse_return_mode, split_size, dim);
}

at::Tensor split_with_sizes_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::split_with_sizes::call(base, split_sizes, dim)[out_index];
  } else {
    return at::_ops::split_with_sizes_copy::call(base, split_sizes, dim)[out_index];
  }
}

at::Tensor split_with_sizes_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::split_with_sizes_inverse(base, mutated_view, inverse_return_mode, out_index, split_sizes, dim);
}

std::shared_ptr<at::functionalization::ViewMeta> split_with_sizes_ViewMeta::to_out_index(int64_t out_index) {
  return std::make_shared<at::functionalization::split_with_sizes_ViewMeta>(has_symbolic_inputs, out_index, reapply_views, inverse_return_mode, split_sizes, dim);
}

at::Tensor squeeze_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::squeeze::call(base);
  } else {
    return at::_ops::squeeze_copy::call(base);
  }
}

at::Tensor squeeze_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::squeeze_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor squeeze__ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::squeeze::call(base);
  } else {
    return at::_ops::squeeze_copy::call(base);
  }
}

at::Tensor squeeze__ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::squeeze_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor squeeze_dim_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::squeeze_dim::call(base, dim);
  } else {
    return at::_ops::squeeze_copy_dim::call(base, dim);
  }
}

at::Tensor squeeze_dim_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::squeeze_dim_inverse(base, mutated_view, inverse_return_mode, dim);
}

at::Tensor squeeze__dim_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::squeeze_dim::call(base, dim);
  } else {
    return at::_ops::squeeze_copy_dim::call(base, dim);
  }
}

at::Tensor squeeze__dim_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::squeeze_dim_inverse(base, mutated_view, inverse_return_mode, dim);
}

at::Tensor squeeze_dims_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::squeeze_dims::call(base, dim);
  } else {
    return at::_ops::squeeze_copy_dims::call(base, dim);
  }
}

at::Tensor squeeze_dims_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::squeeze_dims_inverse(base, mutated_view, inverse_return_mode, dim);
}

at::Tensor squeeze__dims_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::squeeze_dims::call(base, dim);
  } else {
    return at::_ops::squeeze_copy_dims::call(base, dim);
  }
}

at::Tensor squeeze__dims_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::squeeze_dims_inverse(base, mutated_view, inverse_return_mode, dim);
}

at::Tensor t_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::t::call(base);
  } else {
    return at::_ops::t_copy::call(base);
  }
}

at::Tensor t_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::t_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor t__ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::t::call(base);
  } else {
    return at::_ops::t_copy::call(base);
  }
}

at::Tensor t__ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::t_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor transpose_int_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::transpose_int::call(base, dim0, dim1);
  } else {
    return at::_ops::transpose_copy_int::call(base, dim0, dim1);
  }
}

at::Tensor transpose_int_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::transpose_int_inverse(base, mutated_view, inverse_return_mode, dim0, dim1);
}

at::Tensor transpose__ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::transpose_int::call(base, dim0, dim1);
  } else {
    return at::_ops::transpose_copy_int::call(base, dim0, dim1);
  }
}

at::Tensor transpose__ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::transpose_int_inverse(base, mutated_view, inverse_return_mode, dim0, dim1);
}

at::Tensor _nested_view_from_buffer_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_nested_view_from_buffer::call(base, nested_size, nested_strides, offsets);
  } else {
    return at::_ops::_nested_view_from_buffer_copy::call(base, nested_size, nested_strides, offsets);
  }
}

at::Tensor _nested_view_from_buffer_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_nested_view_from_buffer_inverse(base, mutated_view, inverse_return_mode, nested_size, nested_strides, offsets);
}

at::Tensor _nested_view_from_jagged_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_nested_view_from_jagged::call(base, offsets, dummy, lengths, ragged_idx, min_seqlen, max_seqlen);
  } else {
    return at::_ops::_nested_view_from_jagged_copy::call(base, offsets, dummy, lengths, ragged_idx, min_seqlen, max_seqlen);
  }
}

at::Tensor _nested_view_from_jagged_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_nested_view_from_jagged_inverse(base, mutated_view, inverse_return_mode, offsets, dummy, lengths, ragged_idx, min_seqlen, max_seqlen);
}

at::Tensor _nested_get_values_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_nested_get_values::call(base);
  } else {
    return at::_ops::_nested_get_values_copy::call(base);
  }
}

at::Tensor _nested_get_values_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_nested_get_values_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor unsqueeze_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::unsqueeze::call(base, dim);
  } else {
    return at::_ops::unsqueeze_copy::call(base, dim);
  }
}

at::Tensor unsqueeze_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::unsqueeze_inverse(base, mutated_view, inverse_return_mode, dim);
}

at::Tensor unsqueeze__ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::unsqueeze::call(base, dim);
  } else {
    return at::_ops::unsqueeze_copy::call(base, dim);
  }
}

at::Tensor unsqueeze__ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::unsqueeze_inverse(base, mutated_view, inverse_return_mode, dim);
}

at::Tensor _indices_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_indices::call(base);
  } else {
    return at::_ops::_indices_copy::call(base);
  }
}

at::Tensor _indices_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_indices_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor _values_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_values::call(base);
  } else {
    return at::_ops::_values_copy::call(base);
  }
}

at::Tensor _values_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_values_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor indices_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::indices::call(base);
  } else {
    return at::_ops::indices_copy::call(base);
  }
}

at::Tensor indices_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::indices_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor values_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::values::call(base);
  } else {
    return at::_ops::values_copy::call(base);
  }
}

at::Tensor values_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::values_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor crow_indices_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::crow_indices::call(base);
  } else {
    return at::_ops::crow_indices_copy::call(base);
  }
}

at::Tensor crow_indices_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::crow_indices_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor col_indices_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::col_indices::call(base);
  } else {
    return at::_ops::col_indices_copy::call(base);
  }
}

at::Tensor col_indices_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::col_indices_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor ccol_indices_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::ccol_indices::call(base);
  } else {
    return at::_ops::ccol_indices_copy::call(base);
  }
}

at::Tensor ccol_indices_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::ccol_indices_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor row_indices_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::row_indices::call(base);
  } else {
    return at::_ops::row_indices_copy::call(base);
  }
}

at::Tensor row_indices_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::row_indices_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor unbind_int_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::unbind_int::call(base, dim)[out_index];
  } else {
    return at::_ops::unbind_copy_int::call(base, dim)[out_index];
  }
}

at::Tensor unbind_int_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::unbind_int_inverse(base, mutated_view, inverse_return_mode, out_index, dim);
}

std::shared_ptr<at::functionalization::ViewMeta> unbind_int_ViewMeta::to_out_index(int64_t out_index) {
  return std::make_shared<at::functionalization::unbind_int_ViewMeta>(has_symbolic_inputs, out_index, reapply_views, inverse_return_mode, dim);
}

at::Tensor lift_fresh_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::lift_fresh::call(base);
  } else {
    return at::_ops::lift_fresh_copy::call(base);
  }
}

at::Tensor lift_fresh_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::lift_fresh_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor view_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::view::call(base, size);
  } else {
    return at::_ops::view_copy::call(base, size);
  }
}

at::Tensor view_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::view_inverse(base, mutated_view, inverse_return_mode, size);
}

at::Tensor view_dtype_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::view_dtype::call(base, dtype);
  } else {
    return at::_ops::view_copy_dtype::call(base, dtype);
  }
}

at::Tensor view_dtype_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::view_dtype_inverse(base, mutated_view, inverse_return_mode, dtype);
}

at::Tensor unfold_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::unfold::call(base, dimension, size, step);
  } else {
    return at::_ops::unfold_copy::call(base, dimension, size, step);
  }
}

at::Tensor unfold_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::unfold_inverse(base, mutated_view, inverse_return_mode, dimension, size, step);
}

at::Tensor alias_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::alias::call(base);
  } else {
    return at::_ops::alias_copy::call(base);
  }
}

at::Tensor alias_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::alias_inverse(base, mutated_view, inverse_return_mode);
}

at::Tensor _test_autograd_multiple_dispatch_view_ViewMeta::forward(const at::Tensor& base) {
  if (reapply_views) {
    return at::_ops::_test_autograd_multiple_dispatch_view::call(base);
  } else {
    return at::_ops::_test_autograd_multiple_dispatch_view_copy::call(base);
  }
}

at::Tensor _test_autograd_multiple_dispatch_view_ViewMeta::reverse(const at::Tensor& base, const Tensor& mutated_view) {
  return at::functionalization::FunctionalInverses::_test_autograd_multiple_dispatch_view_inverse(base, mutated_view, inverse_return_mode);
}

} // namespace functionalization
} // namespace at
